name: Deploy to GitHub Pages

on:
  push:
    branches: [master] # Changed to match your actual branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Add explicit permissions
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Type Check
        run: npm run check

      - name: Build
        run: npm run build

      - name: List build output
        run: |
          echo "Contents of dist directory:"
          ls -la dist/
          echo "Contents of index.html if it exists:"
          cat dist/index.html || echo "No index.html found"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          token: ${{ secrets.GITHUB_TOKEN }} # Explicitly using the token
          branch: gh-pages
          clean: true # Automatically remove deleted files from the deploy branch
